### ISSUE TITLE
How to generate xlf files

### ISSUE THREAD

**Issue by ghost** [StephenFluin/i18n-sample#1]
I find it hard to reproduce, since I don't know how the .xlf files got generated. Looking at the `package.json`, I didn't find anything which generates the translation files. Is this a feature of the compiler-cli, or did you add those files manually?

On the blogpost for rc.6 the author only mentions a "ng-i18n tool", but I don't know where to get it. Could you elaborate this a little bit in the README?

**Comment by Mattes83** [comment]
You need   "@angular/compiler-cli": "^0.6.0" in your dependencies. then you can add "extract": "ng-xi18n" in your scripts section and create the xliff file with "npm run extract".

Some official documentation would be nice

**Comment by sensone** [comment]
@StephenFluin , @Mattes83 Could you tell me, how I can generate https://github.com/StephenFluin/i18n-sample/blob/master/src/messages.fr.ts from https://github.com/StephenFluin/i18n-sample/blob/master/src/messages.fr.xlf ? 😄

**Comment by ghost** [comment]
Thank you @Mattes83, what a shame that it doesn't work for me because a library I am using does not support `compiler-cli` :/
If `.xlf` is anything similar to `.po`, then you don't need anything but the `messages.xlf`. A translate program can then read the `messages.xlf` and create a localization for each language. For `.po`, a great program for this is `POEdit`. But I'm afraid that there is no good software for `.xlf`. At least I have not found anything after a quick google search.
Anyway, I find it problematic to make a wrapper `.ts` file like `messages.fr.ts` in this example. This is just redundant and verbose. Can't this be solved better?

**Comment by StephenFluin** [comment]
@sensone I manually took the contents of the .xlf file and put it into a variable within a TS file so that I could use it as part of bootstrapping in JIT mode.  If you want, you can pass the .xlf file to `ngc` as part of AOT compilation, then you never need the .ts file.

**Comment by sensone** [comment]
@StephenFluin, thank you 👌
